#ifndef CMARK_GFM_EXPORT_H
#define CMARK_GFM_EXPORT_H

#define CMARK_GFM_EXPORT
#define CMARK_GFM_NO_EXPORT
#define CMARK_GFM_DEPRECATED
#define CMARK_GFM_DEPRECATED_EXPORT
#define CMARK_GFM_DEPRECATED_NO_EXPORT

#endif
